options:
  formatter: stylish
files:
  include: 'public/**/*.s+(a|c)ss'
rules:
  class-name-format:
    - 2
    -
      convention: 'hyphenatedbem'

  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals: 0
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties:
    - 2
    -
      exclude:
        - background
        - src
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 1
  no-url-domains: 1
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 2

  # Nesting
  bem-depth: 3
  declarations-before-nesting: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  function-name-format: 0 
  mixin-name-format: 0
  placeholder-name-format: 0
  variable-name-format: 0

  # Style Guide
  border-zero: 2
  brace-style: 2
  clean-import-paths: 
    - 1
    -
      leading-underscore: true
  empty-args: 2
  hex-length: 2
  hex-notation: 2
  indentation: 
    - 2
    -
      size: 4

  leading-zero: 2
  nesting-depth: 0
  property-sort-order: 0
  pseudo-element: 2
  quotes: 1
  attribute-quotes: 0

  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2