version: 2
jobs:
  build:
    docker:
      - image: thingsthat/thingsthat-circleci:latest

    working_directory: ~/src
    
    branches:
      only:
        - master
  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: install packages
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint

      - run:
          name: npm build
          command: npm run build

      - run:
          name: deploy to S3
          command: aws s3 sync dist/ s3://thingsthat.com --region eu-west-1 --delete

      - run:
          name: invalidate cloudfront
          command: aws cloudfront create-invalidation --distribution-id=E2WHZPGLTYGXGS --paths "/*"
